# Dockerfile.frontend

# Stage 1: Build the React application
FROM node:20 as builder

WORKDIR /app

COPY ./frontend/package*.json ./
RUN npm install
ARG BACKEND_HOST
ENV BACKEND_HOST=$BACKEND_HOST

COPY ./frontend .
RUN npm run build

# Stage 2: Serve the static files with Nginx
FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d/

COPY --from=builder /app/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
