version: "3.9"

services:
  db:
    image: postgres:17
    container_name: db
    # env_file:
    #   - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - appnet


  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    depends_on:
      - db
    volumes:
      - backend_static_volume:/app/staticfiles
      - backend_media_volume:/app/media
    env_file:
      - .env
    networks:
      - appnet
    #command: ["/bin/sh", "-c", "while true; do sleep 1000; done"]
    command: ["/bin/sh", "/app/run.sh"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        BACKEND_HOST: ${BACKEND_HOST}
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - backend_static_volume:/app/staticfiles
      - backend_media_volume:/app/media
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    restart: always
    networks:
      - appnet


volumes:
  db_data:
  backend_static_volume:
  backend_media_volume:

networks:
  appnet:
    driver: bridge
