/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * Shop API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
import { Configuration } from "./configuration";
export * from "./api";
export * from "./configuration";

const apiConfig = new Configuration({
    basePath: "http://localhost:8000",
});

export { apiConfig };
